[package]
name = "os"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true

# Feature flags for selecting the board support package
[features]
# default bsp so rust-analyzer works
default = ["bsp_rpi4"]
bsp_rpi4 = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
aarch64-cpu = "10.0.0"
