.text
.global el1_vector_table
.section .text._el1_vector_table

.balign 2048
el1_vector_table:

/* exceptions from current EL while using the SP_EL0 stack (exceptions from kernel)*/
  /* Synchronous */ 
  .balign 0x80
  bl _unhandled_exception 
  /* IRQ */
  .balign 0x80
  bl _unhandled_exception 
  /* FIQ */
  .balign 0x80
  bl _unhandled_exception 
  /* SError */
  .balign 0x80
  bl _unhandled_exception 

/* exceptions from current EL while using the SP_ELx stack (exceptions from kernel)*/
  /* Synchronous */ 
  .balign 0x80
  b synchronous_kernel_exception_entry
  /* IRQ */
  .balign 0x80
  bl _unhandled_exception 
  /* FIQ */
  .balign 0x80
  bl _unhandled_exception 
  /* SError */
  .balign 0x80
  bl _unhandled_exception 

/* exceptions from lower EL and at least one lower el is running 64 bit (exceptions from userspace)*/
  /* Synchronous */ 
  .balign 0x80
  bl _unhandled_exception
  /* IRQ */
  .balign 0x80
  bl _unhandled_exception
  /* FIQ */
  .balign 0x80
  bl _unhandled_exception
  /* SError */
  .balign 0x80
  bl _unhandled_exception

/* exceptions from lower EL and all lower el are running 32 bit (should never happen)*/
  /* Synchronous */ 
  .balign 0x80
  bl _unhandled_exception
  /* IRQ */
  .balign 0x80
  bl _unhandled_exception
  /* FIQ */
  .balign 0x80
  bl _unhandled_exception
  /* SError */
  .balign 0x80
  bl _unhandled_exception

/*
  saves all general purpose registers that have to be caller saved
  and calls into rust code, all other registers should be saved
  by the code generated by rustc
*/
synchronous_kernel_exception_entry:
  sub sp, sp, #192
  stp x0, x1, [sp, #0]
  stp x2, x3, [sp, #16]
  stp x4, x5, [sp, #32]
  stp x6, x7, [sp, #48]
  stp x8, x9, [sp, #64]
  stp x10, x11, [sp, #80]
  stp x12, x13, [sp, #96]
  stp x14, x15, [sp, #112]
  stp x16, x17, [sp, #128]
  stp x18, x29, [sp, #144]
  stp x30, xzr, [sp, #160]

  mrs x0, ESR_EL1
  mrs x1, FAR_EL1
  stp x0, x1, [sp, #176]

  /* save the pointer to the registers saved on the stack 
  as the first argument for access from rust code */
  mov x0, sp
  /* store all the float/simd registers */
  sub sp, sp, #512
  str q0, [sp, #0]
  str q1, [sp, #16]
  str q2, [sp, #32]
  str q3, [sp, #48]
  str q4, [sp, #64]
  str q5, [sp, #80]
  str q6, [sp, #96]
  str q7, [sp, #112]
  str q8, [sp, #128]
  str q9, [sp, #144]
  str q10, [sp, #160]
  str q11, [sp, #176]
  str q12, [sp, #192]
  str q13, [sp, #208]
  str q14, [sp, #224]
  str q15, [sp, #240]
  str q16, [sp, #256]
  str q17, [sp, #272]
  str q18, [sp, #288]
  str q19, [sp, #304]
  str q20, [sp, #320]
  str q21, [sp, #336]
  str q22, [sp, #352]
  str q23, [sp, #368]
  str q24, [sp, #384]
  str q25, [sp, #400]
  str q26, [sp, #416]
  str q27, [sp, #432]
  str q28, [sp, #448]
  str q29, [sp, #464]
  str q30, [sp, #480]
  str q31, [sp, #496]
  
  /* call into rust code with the pointer to the saved registers as the first argument */
  bl _synchronous_kernel_exception

  /* restore simd regs */
  ldr q0, [sp, #0]
  ldr q1, [sp, #16]
  ldr q2, [sp, #32]
  ldr q3, [sp, #48]
  ldr q4, [sp, #64]
  ldr q5, [sp, #80]
  ldr q6, [sp, #96]
  ldr q7, [sp, #112]
  ldr q8, [sp, #128]
  ldr q9, [sp, #144]
  ldr q10, [sp, #160]
  ldr q11, [sp, #176]
  ldr q12, [sp, #192]
  ldr q13, [sp, #208]
  ldr q14, [sp, #224]
  ldr q15, [sp, #240]
  ldr q16, [sp, #256]
  ldr q17, [sp, #272]
  ldr q18, [sp, #288]
  ldr q19, [sp, #304]
  ldr q20, [sp, #320]
  ldr q21, [sp, #336]
  ldr q22, [sp, #352]
  ldr q23, [sp, #368]
  ldr q24, [sp, #384]
  ldr q25, [sp, #400]
  ldr q26, [sp, #416]
  ldr q27, [sp, #432]
  ldr q28, [sp, #448]
  ldr q29, [sp, #464]
  ldr q30, [sp, #480]
  ldr q31, [sp, #496]

  add sp, sp, #512

  /* restore general purpose regs */
  ldp x0, x1, [sp, #0]
  ldp x2, x3, [sp, #16]
  ldp x4, x5, [sp, #32]
  ldp x6, x7, [sp, #48]
  ldp x8, x9, [sp, #64]
  ldp x10, x11, [sp, #80]
  ldp x12, x13, [sp, #96]
  ldp x14, x15, [sp, #112]
  ldp x16, x17, [sp, #128]
  ldp x18, x29, [sp, #144]
  ldp x30, xzr, [sp, #160]
  add sp, sp, #192
  eret
